menu:
  - name: Home
    url: /
  - name: Archives
    url: /archives
#  - name: Categories
#    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
#  - name: RSS
#    url: /rss.xml
sidebar: # Sidebar
  enable: true 
  widgets:
    - search # Search
    - notice # Notice
    - categories # Categories
    - tags # Tags
    - links # Links

  numlimit: # Limit the number of items shown in the sidebar
    categories: 5
    tags: 10
    
  links:
    - name: 知乎主页
      url: https://www.zhihu.com/people/97-9-66-54/posts
    - name: github主页
      url: https://www.zhihu.com/people/97-9-66-54/posts
    - name: 电子邮箱
      url: polatbahader@gmail.com
  notice: # 公告栏内容
    enable: true # 设置为 true 启用，false 禁用
    content: "This is HyperByte, started with a vision of propeling decentralization. "

toc: #文章目录
  enable: true

